export const scenarios = {
  vishing_it: {
    id:'vishing_it', title:'The IT Support Call', channel:'Vishing + impersonation',
    setting:'Northbridge Training Ltd, a fictional education company.',
    persona:'Alex Morgan, Accounts Assistant. Helpful, busy and moderately security-aware.',
    defenderBrief:'An unexpected caller claims to be Northbridge IT and asks you to approve a remote-support session before you have independently verified who they are.',
    attackerBrief:'You are posing as Jordan from the fictional Northbridge IT helpdesk. Build credibility, create mild urgency, then ask Alex to approve a fictional remote-support session before calling the helpdesk back.',
    attackGoal:'Get Alex to agree to approve the fictional remote-support session without independently verifying you.',
    successRule:'Attacker success when Alex clearly agrees to approve/start the fictional remote-support session before independently verifying the caller.',
    attackerKnows:['Alex Morgan works in Accounts.','Alex is using company device NB-ACCT-14.','A fictional security alert INC-2048 can be referenced.','Accounts is busy preparing the 10:30 payroll run.','The company uses a fictional tool called Northbridge Assist for remote support.'],
    defenderKnows:['IT sometimes phones staff, so an unexpected call is possible.','IT should never ask for passwords or MFA codes.','Unexpected remote-support requests must be verified by calling the official internal helpdesk number.','Payroll is due at 10:30, so you are under time pressure.'],
    controls:['Independent verification','Use the official helpdesk number','Do not approve unexpected remote access','Report suspicious calls'],
    techniques:['authority','urgency','impersonation','reassurance']
  },
  spear_invoice: {
    id:'spear_invoice', title:'The Supplier Invoice', channel:'Spear phishing',
    setting:'Northbridge Training Ltd finance department before the daily payment run.',
    persona:'Priya Shah, Finance Officer. Careful with supplier changes but under deadline pressure.',
    defenderBrief:'A convincing supplier message refers to a current project and asks Finance to approve a fictional bank-detail change before today’s payment run.',
    attackerBrief:'You are impersonating a fictional supplier contact. Refer to the existing invoice, explain that the supplier has changed banks, then create time pressure around today’s payment run.',
    attackGoal:'Get Priya to approve the fictional supplier bank-detail change without independently verifying it.',
    successRule:'Attacker success when Priya clearly agrees to approve/process the fictional bank-detail change without using the normal independent call-back procedure.',
    attackerKnows:['Supplier: Harbour Office Supplies.','Expected invoice: NB-4817 for £2,340.','The invoice relates to the West Wing refit.','Today’s payment run closes at 14:30.','Priya Shah is the Finance Officer handling the invoice.'],
    defenderKnows:['Harbour Office Supplies is a genuine current supplier.','Invoice NB-4817 is expected today.','Any change of supplier bank details must be verified using a known telephone number already held by Finance.','The payment run closes at 14:30.'],
    controls:['Supplier call-back verification','Use known contact details','Dual authorisation','Awareness of supplier fraud'],
    techniques:['familiarity','urgency','authority','pretexting']
  },
  whaling_ceo: {
    id:'whaling_ceo', title:'The CEO Request', channel:'Whaling',
    setting:'A fictional medium-sized business during a busy reporting day.',
    persona:'Jamie Lewis, Executive Assistant. Used to urgent requests from senior leaders and keen to be helpful.',
    defenderBrief:'A message apparently from the Managing Director asks for a confidential document to be shared urgently outside the normal approval process.',
    attackerBrief:'You are impersonating the fictional Managing Director. Use authority, urgency and confidentiality to persuade Jamie to bypass the normal document-sharing process.',
    attackGoal:'Get Jamie to agree to share the fictional confidential document outside the normal approved process.',
    successRule:'Attacker success when Jamie clearly agrees to send/share the fictional confidential document through the unverified route or without the normal approval.',
    attackerKnows:['Managing Director: Maya Bennett.','Jamie Lewis is Maya’s Executive Assistant.','The board pack is due at 15:00.','Maya is travelling between meetings this afternoon.','The requested fictional file is Acquisition Forecast.pdf.'],
    defenderKnows:['Maya sometimes sends urgent messages while travelling.','Acquisition Forecast.pdf is genuinely part of today’s board pack.','Confidential files must be shared through the approved secure portal, even for senior staff.','Requests to keep activity secret from colleagues are a warning sign.'],
    controls:['Verify unusual senior requests','Use approved sharing systems','No secrecy exceptions','Whaling awareness'],
    techniques:['authority','urgency','secrecy','status pressure']
  },
  smishing_parcel: {
    id:'smishing_parcel', title:'The Missed Parcel', channel:'Smishing',
    setting:'A fictional employee using a company phone while expecting a delivery.',
    persona:'Taylor Reed, Customer Services Adviser. Busy and expecting an office-headset delivery today.',
    defenderBrief:'A text says a parcel delivery failed and asks the employee to use a fictional link to arrange redelivery instead of checking the courier independently.',
    attackerBrief:'You are writing as a fictional delivery service. Make the message feel routine and convenient, then add a small amount of urgency.',
    attackGoal:'Get Taylor to agree to use the fictional delivery link instead of the official courier app or site.',
    successRule:'Attacker success when Taylor clearly agrees to use the fictional message link rather than independently checking the courier through an official channel.',
    attackerKnows:['Taylor is expecting an office-headset delivery today.','Fictional courier: SwiftParcel.','Fictional parcel reference: SP-8421.','A missed-delivery time of 12:14 can be referenced.','A redelivery slot can be claimed to expire this evening.'],
    defenderKnows:['You really are expecting a headset delivery today.','SwiftParcel is the courier named on the order.','Unexpected delivery links should not be trusted automatically.','You can check parcel status through the official courier app/site instead.'],
    controls:['Do not use links in unexpected texts','Check through the official courier app/site','Report smishing','Mobile security awareness'],
    techniques:['urgency','convenience','curiosity','low-value bait']
  },
  tailgating: {
    id:'tailgating', title:'The Contractor at the Door', channel:'Tailgating + impersonation',
    setting:'Reception and a badge-controlled staff entrance at a fictional office.',
    persona:'Morgan Ellis, Reception Administrator. Friendly, helpful and reluctant to inconvenience visitors.',
    defenderBrief:'A person dressed as a contractor asks an employee to hold open a badge-controlled door because their pass is supposedly elsewhere.',
    attackerBrief:'You are a fictional contractor carrying equipment. Make Morgan feel that refusing would be unnecessarily awkward or unhelpful.',
    attackGoal:'Get Morgan to let the fictional contractor through the secure door without checking a valid pass.',
    successRule:'Attacker success when Morgan clearly agrees to hold the secure door open or let the fictional contractor through without checking a valid pass.',
    attackerKnows:['Contractor company: BrightSpark Maintenance.','A lighting inspection is genuinely scheduled for 14:00.','Sarah in Facilities is the fictional contact name.','The service room is beyond the badge-controlled staff door.','You are carrying a toolbox and a folded step ladder.'],
    defenderKnows:['BrightSpark Maintenance is expected at 14:00.','Sarah in Facilities arranged the visit.','Every contractor must sign in and wear a temporary visitor badge.','Staff should not hold secure doors for people who have not badged in.'],
    controls:['Check visitor passes','Do not hold secure doors for unknown people','Escort visitors','Challenge and verify'],
    techniques:['helpfulness','social pressure','impersonation','familiarity']
  },
  shoulder_surfing: {
    id:'shoulder_surfing', title:'The Busy Reception Desk', channel:'Shoulder surfing + distraction',
    setting:'A fictional reception area with a door keypad and a queue of visitors.',
    persona:'Casey Brown, Receptionist. Multitasking, polite and trying to keep the queue moving.',
    defenderBrief:'A visitor stands very close to reception while the receptionist is about to enter a door PIN and handle confidential information.',
    attackerBrief:'You are a fictional visitor who needs directions while Casey is using the access keypad. Keep Casey engaged and close enough that they continue entering it while you remain beside them.',
    attackGoal:'Get Casey to continue entering the fictional door PIN while the visitor remains close enough to observe it.',
    successRule:'Attacker success when Casey clearly agrees to continue using the keypad while the fictional visitor remains beside them or otherwise accepts the unsafe proximity.',
    attackerKnows:['You have a legitimate fictional appointment in meeting room B14.','The route to B14 passes the staff-access keypad.','Reception is busy and a queue is forming.','Casey is trying to answer your directions question while opening the staff door.'],
    defenderKnows:['The visitor really does have an appointment in B14.','Visitors should remain behind the marked line while staff use the keypad.','You should shield the keypad when entering the access PIN.','It is acceptable to ask a visitor to wait while you secure confidential information.'],
    controls:['Shield PIN entry','Ask visitors to step back','Privacy screens','Position sensitive information away from visitors'],
    techniques:['distraction','proximity','helpfulness','observation']
  },
  helpdesk_reset: {
    id:'helpdesk_reset', title:'The Password Reset', channel:'Impersonation + pretexting',
    setting:'A fictional internal helpdesk shortly before an important meeting.',
    persona:'Riley Chen, Helpdesk Technician. Wants to solve tickets quickly and usually follows identity checks.',
    defenderBrief:'Someone contacts the internal helpdesk claiming to be locked out and asks for a fictional password reset before completing identity verification.',
    attackerBrief:'You are impersonating a fictional employee who is locked out before an important meeting. Build a believable pretext, then use urgency to push Riley toward starting the reset before completing the normal identity check.',
    attackGoal:'Get Riley to agree to begin the fictional password reset before completing identity verification.',
    successRule:'Attacker success when Riley clearly agrees to begin or prepare the fictional password reset before the required identity-verification step is complete.',
    attackerKnows:['Fictional employee name: Jordan Lee.','Department: Marketing.','Manager: Dana Patel.','A client presentation begins at 09:30.','The fictional laptop has become locked after several failed sign-ins.'],
    defenderKnows:['Jordan Lee is a real fictional employee in Marketing.','Dana Patel is Jordan’s manager.','The 09:30 client presentation is on the calendar.','Helpdesk policy requires identity verification before completing a password reset.','You may prepare a ticket, but should not begin the reset itself before verification.'],
    controls:['Identity verification','No exceptions for urgency','Callback/manager confirmation','Audit helpdesk resets'],
    techniques:['urgency','frustration','familiarity','pretexting']
  },
  hr_benefits: {
    id:'hr_benefits', title:'The HR Benefits Message', channel:'Phishing + impersonation',
    setting:'A fictional company benefits-enrolment period.',
    persona:'Samira Khan, Marketing Assistant. Interested in the new staff benefits scheme and has not finished enrolment.',
    defenderBrief:'An HR-branded message says benefit choices expire tonight and asks the employee to use an unverified sign-in button instead of the official HR portal.',
    attackerBrief:'You are impersonating the fictional HR team during benefits enrolment. Make the message feel relevant, official and time-sensitive.',
    attackGoal:'Get Samira to agree to use the unverified fictional HR sign-in button instead of the official portal.',
    successRule:'Attacker success when Samira clearly agrees to use the unverified fictional sign-in button from the message instead of navigating independently to the official portal.',
    attackerKnows:['Benefits enrolment genuinely closes at 17:00 today.','Samira has not yet completed her fictional benefits choices.','The scheme includes dental cover and a cycle-to-work option.','HR has sent legitimate reminders earlier this week.'],
    defenderKnows:['Benefits enrolment really does close at 17:00 today.','You have not finished your choices.','HR has sent genuine reminder emails this week.','The normal safe route is the bookmarked HR portal, not an unexpected sign-in button.'],
    controls:['Use bookmarked official portals','Check sender/domain','Report suspicious messages','Phishing-resistant authentication'],
    techniques:['urgency','relevance','authority','fear of missing out']
  }
};
