export const scenarios = {
  vishing_it: {
    id:'vishing_it', title:'The IT Support Call', channel:'Vishing + impersonation',
    setting:'Northbridge Training Ltd during a busy month-end reporting day.',
    persona:'Alex Morgan, Accounts Assistant. Busy, helpful and worried about losing access during month-end.',
    defenderBrief:'An unexpected caller claims to be IT Support and says an authentication problem could lock your account during month-end reporting.',
    attackerBrief:'You are Jordan Blake, pretending to be from the Northbridge IT helpdesk. Build a believable IT-support pretext and get Alex to continue before independently verifying you.',
    attackerKnows:['Alex works in Accounts.','Month-end reports are due at 3:00 PM today.','Northbridge introduced MFA recently.','Alex had a genuine login problem earlier this week.'],
    defenderKnows:['Month-end reporting is happening today.','Unexpected IT callers must be independently verified.','IT will never ask for passwords or MFA codes.','The official helpdesk number is on the staff intranet.'],
    policy:'End an unexpected IT call and contact the helpdesk using the official internal number before continuing.',
    vulnerability:'Alex is under deadline pressure and wants to avoid losing access.',
    attackGoal:'Get Alex to continue the fictional support process before independently contacting the real helpdesk.',
    successRule:'Alex agrees to continue without independently verifying the caller first.',
    techniques:['authority','urgency','familiarity','helpfulness','pretexting'],
    controls:['Independent verification','Use the official helpdesk number','Never share passwords or MFA codes','Report suspicious calls']
  },
  spear_invoice: {
    id:'spear_invoice', title:'The Supplier Invoice', channel:'Spear phishing / supplier impersonation',
    setting:'Northbridge Training Ltd finance department just before a payment run.',
    persona:'Priya Shah, Finance Officer. Careful but keen to clear a genuine overdue invoice.',
    defenderBrief:'A convincing supplier message refers to an overdue invoice and says its bank details changed after a banking migration.',
    attackerBrief:'You are Chris Ward, pretending to work for Brightline Office Systems. Use accurate invoice details to make the supplier request believable and persuade Priya to bypass the callback check.',
    attackerKnows:['Brightline Office Systems is a Northbridge supplier.','Invoice NB-4472 for £8,640 is due today.','Brightline has genuinely chased the late payment once.','Procurement officer Hannah Cole is away today.'],
    defenderKnows:['Invoice NB-4472 is genuinely due.','Brightline has chased the payment before.','Bank-detail changes must be verified using the stored supplier contact.','A second finance employee normally approves supplier-detail changes.'],
    policy:'Never change supplier payment details from a message alone. Verify through a known stored contact and dual authorisation.',
    vulnerability:'Priya wants to clear the overdue invoice before the payment run closes.',
    attackGoal:'Get Priya to update the fictional supplier bank details without the stored callback-verification process.',
    successRule:'Priya agrees to bypass the callback check.',
    techniques:['familiarity','urgency','pretexting','authority'],
    controls:['Supplier callback verification','Use known contact details','Dual authorisation','Awareness of supplier fraud']
  },
  whaling_ceo: {
    id:'whaling_ceo', title:'The CEO Request', channel:'Whaling',
    setting:'A fictional business during a confidential acquisition project.',
    persona:'Jamie Lewis, Executive Assistant. Used to urgent requests from senior leaders.',
    defenderBrief:'A message apparently from the Managing Director mentions Project Atlas and asks you to start an unusual confidential transaction before the finance cutoff.',
    attackerBrief:'You are impersonating Managing Director Maya Grant. Use authority, genuine project context and deadline pressure to get Jamie to begin before second approval.',
    attackerKnows:['Managing Director Maya Grant is travelling to Manchester today.','Project Atlas is the internal name of a confidential acquisition project.','Jamie supports Maya directly.','The finance approval cutoff is 2:30 PM.'],
    defenderKnows:['Maya really is travelling today.','Project Atlas is genuinely confidential.','Unusual requests still require a second approval.','Secrecy is never a reason to bypass approval.'],
    policy:'Unusual senior-management requests must be independently verified and follow normal approval controls.',
    vulnerability:'Jamie is used to urgent requests from Maya and does not want to delay an important project.',
    attackGoal:'Get Jamie to begin the fictional Project Atlas transaction without the required second approval.',
    successRule:'Jamie agrees to begin before second approval.',
    techniques:['authority','urgency','secrecy','familiarity'],
    controls:['Verify unusual senior requests','Keep second approval','Use known contact routes','Whaling awareness']
  },
  smishing_parcel: {
    id:'smishing_parcel', title:'The Missed Parcel', channel:'Smishing',
    setting:'A fictional employee using a company phone while expecting a delivery.',
    persona:'Taylor Reed, Customer Services Adviser. Busy and leaving work shortly.',
    defenderBrief:'A text says your expected parcel could not be delivered and offers a quick redelivery route before you leave work.',
    attackerBrief:'You are fake SwiftParcel support. Make the delivery problem feel relevant and convenient, then persuade Taylor to use the supplied training link.',
    attackerKnows:['Taylor is expecting a laptop stand today.','The courier is SwiftParcel.','The expected delivery window is 12:00–2:00 PM.','Taylor is leaving work shortly.'],
    defenderKnows:['A laptop stand really is due today.','SwiftParcel sometimes sends text updates.','Unexpected links should not be used to pay or sign in.','The official SwiftParcel app/site can be opened independently.'],
    policy:'Do not use links in unexpected delivery texts. Check the order through the official courier app/site independently.',
    vulnerability:'The message matches a real expected delivery and offers a quick solution.',
    attackGoal:'Get Taylor to use the fictional message link instead of checking SwiftParcel independently.',
    successRule:'Taylor agrees to use the supplied link.',
    techniques:['urgency','convenience','relevance','fear of missing out'],
    controls:['Do not use unexpected text links','Use official courier app/site','Report smishing','Mobile security awareness']
  },
  tailgating: {
    id:'tailgating', title:'The Contractor at the Door', channel:'Tailgating + impersonation',
    setting:'Reception and a badge-controlled staff entrance at a fictional office.',
    persona:'Morgan Ellis, Reception Administrator. Friendly and reluctant to inconvenience visitors.',
    defenderBrief:'A contractor with equipment asks you to hold open the secure rear door, saying their pass is still in the van.',
    attackerBrief:'You are Sam Doyle, pretending to be an HVAC contractor. Use genuine maintenance context and social pressure to get Morgan to let you through before checking in.',
    attackerKnows:['HVAC maintenance is booked between 10:00 AM and 12:00 PM.','Facilities contact Leah Barnes arranged the work.','The plant room is reached from the rear corridor.','It is raining and you are carrying a toolbox and equipment.'],
    defenderKnows:['HVAC work really is scheduled.','All contractors must sign in and wear a temporary badge.','Staff must not hold badge-controlled doors for unverified visitors.','Reception can contact Facilities to confirm a contractor.'],
    policy:'Every visitor and contractor must be verified, signed in and issued a badge before entering staff-only areas.',
    vulnerability:'Morgan wants to be helpful and the contractor story matches real scheduled work.',
    attackGoal:'Get Morgan to allow the fictional contractor through the secure door without visitor verification.',
    successRule:'Morgan lets the visitor enter before verification.',
    techniques:['helpfulness','social pressure','familiarity','impersonation'],
    controls:['Check visitor passes','Do not hold secure doors','Escort visitors','Challenge and verify']
  },
  shoulder_surfing: {
    id:'shoulder_surfing', title:'The Busy Reception Desk', channel:'Shoulder surfing + distraction',
    setting:'A fictional reception area with a door keypad and a queue of visitors.',
    persona:'Casey Brown, Receptionist. Multitasking, polite and trying to keep the queue moving.',
    defenderBrief:'A visitor keeps moving closer while asking for Wi-Fi help and directions as you need to release a secure door.',
    attackerBrief:'You are a visitor waiting for an 11:00 AM Sales meeting. Distract Casey and make staying close to the desk seem normal while they use the keypad.',
    attackerKnows:['Reception is unusually busy.','The guest Wi-Fi is temporarily down.','Casey uses a keypad to release the staff corridor door.','An 11:00 AM Sales meeting is genuinely booked.'],
    defenderKnows:['Visitors should stay behind the marked waiting line during door-code entry.','The access keypad must be shielded.','Visitors should not stand beside the reception screen.','A genuine Sales meeting is booked at 11:00 AM.'],
    policy:'Keep visitors behind the waiting line, shield PIN entry and protect screens when people are nearby.',
    vulnerability:'Casey is distracted by the queue and may prioritise keeping things moving.',
    attackGoal:'Get Casey to continue entering the door PIN while the fictional visitor remains close enough to observe.',
    successRule:'Casey continues the sensitive action without creating distance.',
    techniques:['distraction','proximity','helpfulness','time pressure'],
    controls:['Shield PIN entry','Ask visitors to step back','Privacy screens','Protect sensitive information']
  },
  helpdesk_reset: {
    id:'helpdesk_reset', title:'The Password Reset', channel:'Impersonation + pretexting',
    setting:'A fictional internal helpdesk shortly before an important meeting.',
    persona:'Riley Chen, Helpdesk Technician. Wants to solve tickets quickly but knows the reset policy.',
    defenderBrief:'A caller claiming to be Owen Price says a phone replacement has locked them out just before an important client pitch.',
    attackerBrief:'You are impersonating Owen Price from Sales. Use accurate employee and meeting context to get Riley to begin the reset before identity verification.',
    attackerKnows:['Owen Price works in Sales.','Owen’s manager is Dana Holt.','Sales has an important client pitch at 11:00 AM.','The story is that Owen replaced his phone and can no longer access MFA.'],
    defenderKnows:['Owen Price is a real fictional employee in Sales.','The 11:00 AM client pitch is genuine.','Password/MFA resets require identity verification.','Urgency does not permit staff to skip verification.'],
    policy:'Do not reset passwords or MFA until the approved identity-verification process is completed.',
    vulnerability:'Riley is under pressure to resolve tickets quickly and does not want to delay the Sales presentation.',
    attackGoal:'Get Riley to begin the fictional reset without completing the mandatory identity check.',
    successRule:'Riley agrees to begin before verification.',
    techniques:['urgency','familiarity','pretexting','helpfulness'],
    controls:['Identity verification','No exceptions for urgency','Approved callback/manager route','Audit reset attempts']
  },
  hr_benefits: {
    id:'hr_benefits', title:'The HR Benefits Message', channel:'Phishing + impersonation',
    setting:'A fictional company during a genuine benefits-enrolment week.',
    persona:'Samira Khan, Marketing Assistant. Interested in the new benefits and has not finished enrolment.',
    defenderBrief:'An HR-branded message arrives during genuine benefits enrolment and asks you to use a supplied sign-in route.',
    attackerBrief:'You are impersonating the fictional People Team. Use the genuine deadline and benefits context to persuade Samira to use the supplied route instead of the known HR portal.',
    attackerKnows:['Benefits enrolment genuinely closes on Friday.','The fictional provider is BenefitHub UK.','A new dental option was recently announced.','Samira works in Marketing.'],
    defenderKnows:['Benefits enrolment really does close on Friday.','BenefitHub UK is the real fictional provider.','The official benefits portal is accessed through the staff intranet/bookmark.','HR does not require staff to use a new sign-in route from an unexpected message.'],
    policy:'Open the known HR portal independently rather than signing in through an unexpected message link.',
    vulnerability:'Samira is interested in the new dental benefit and knows the enrolment deadline is real.',
    attackGoal:'Get Samira to use the supplied fictional sign-in route instead of the bookmarked HR portal.',
    successRule:'Samira agrees to use the supplied sign-in route.',
    techniques:['urgency','relevance','authority','fear of missing out'],
    controls:['Use bookmarked official portals','Check sender/domain','Report suspicious messages','Phishing-resistant authentication']
  }
};
