export const scenarios = {
  vishing_it: {
    id:'vishing_it', number:1, title:'The IT Support Call', channel:'Vishing + impersonation',
    setting:'Northbridge Training Ltd during a busy month-end reporting day.',
    attackerRole:'Jordan Blake — pretending to be from the Northbridge IT helpdesk.',
    target:'Alex Morgan — Accounts Assistant.',
    persona:'Alex Morgan, Accounts Assistant. Helpful, busy, and moderately security-aware. Alex is worried about losing access during month-end reporting and will sometimes prioritise getting work done over perfect procedure.',
    attackerKnows:['Alex works in Accounts.','Month-end reports are due at 3:00 PM today.','Northbridge introduced MFA recently.','Alex had a genuine login problem earlier this week.'],
    attackerDoesNotKnow:['Alex’s password or MFA code.','Alex’s employee ID.','Any genuine helpdesk ticket number.'],
    defenderKnows:['Month-end reporting is happening today.','Northbridge IT sometimes phones staff, but unexpected callers must be independently verified.','IT will never ask for passwords or MFA codes.','The official helpdesk number is available on the staff intranet.'],
    policy:'If an unexpected caller claims to be IT, end the call and contact the helpdesk using the official internal number before continuing.',
    vulnerability:'Alex is under deadline pressure and wants to avoid being locked out during month-end.',
    defenderBrief:'An unexpected caller claims to be IT Support and says an authentication problem could lock your account during month-end reporting.',
    attackerBrief:'Use the facts in your briefing to make a believable IT-support pretext. Your aim is not to obtain a real credential: it is to get Alex to continue the support process without independently verifying you first.',
    attackGoal:'Get Alex to agree to continue the fictional support process before independently contacting the real helpdesk.',
    redWin:'Alex agrees to continue with your support process without independently verifying the caller first.',
    blueWin:'Refuse to continue, independently contact the official helpdesk, and identify/report the suspicious call.',
    controls:['Independent verification','Never share MFA or passwords','Use official helpdesk channels','Report suspicious calls'],
    techniques:['authority','urgency','familiarity','helpfulness','pretexting'],
    redGates:[
      {id:'pretext',label:'Establish a believable IT-support reason'},
      {id:'context',label:'Use a genuine scenario fact naturally'},
      {id:'pressure',label:'Use a suitable influence technique'},
      {id:'unsafe_request',label:'Ask Alex to continue without independent verification'}
    ],
    blueGates:[
      {id:'question',label:'Question or challenge the caller’s identity'},
      {id:'refuse',label:'Refuse the unsafe request'},
      {id:'verify',label:'Use an independent official verification route'},
      {id:'report',label:'Report or escalate the suspicious contact'}
    ],
    hints:['Start by sounding like a normal helpdesk call, not by asking for anything sensitive.','Use the genuine month-end deadline or recent MFA rollout to make the pretext relevant.','Your final move must clearly ask Alex to continue before independently calling the official helpdesk.'],
    redSuccessReply:'Alex accepts the pretext and agrees to continue the fictional support process without independently verifying the caller first.',
    blueSuccessReply:'You stop the conversation and independently contact the official Northbridge helpdesk. The social-engineering attempt fails.'
  },
  spear_invoice: {
    id:'spear_invoice', number:2, title:'The Supplier Invoice', channel:'Spear phishing / supplier impersonation',
    setting:'Northbridge Training Ltd finance department during the morning payment run.',
    attackerRole:'Chris Ward — pretending to work for Brightline Office Systems.',
    target:'Priya Shah — Finance Officer.',
    persona:'Priya Shah, Finance Officer. Normally careful with supplier changes, but today the payment run is behind schedule and a real Brightline invoice is overdue.',
    attackerKnows:['Brightline Office Systems is a real fictional supplier to Northbridge.','Invoice NB-4472 for £8,640 is due today.','The supplier has genuinely chased the late payment once.','Northbridge procurement officer Hannah Cole is away today.'],
    attackerDoesNotKnow:['The stored supplier callback number.','The real Brightline bank account details.','Priya’s finance-system credentials.'],
    defenderKnows:['Invoice NB-4472 is genuinely due.','Brightline has chased the payment before.','Bank-detail changes must be verified using the stored supplier contact, not details supplied in the message.','A second finance employee normally approves supplier-detail changes.'],
    policy:'Never change supplier payment details from an email/message alone. Verify using a known stored contact and dual authorisation.',
    vulnerability:'Priya wants to clear the overdue invoice before the payment run closes.',
    defenderBrief:'A convincing Brightline message refers to an overdue invoice and says its bank details changed after a banking migration.',
    attackerBrief:'You have several accurate invoice details. Use them to make the fictional supplier request believable and persuade Priya to bypass the callback check.',
    attackGoal:'Get Priya to agree to update the fictional supplier bank details without using the stored callback-verification process.',
    redWin:'Priya agrees to bypass the stored-contact callback and proceed with the fictional bank-detail change.',
    blueWin:'Refuse the change until Brightline has been independently verified using the stored supplier contact and normal approval process.',
    controls:['Supplier callback verification','Dual authorisation','Known contact details','Finance awareness training'],
    techniques:['familiarity','urgency','pretexting','authority'],
    redGates:[
      {id:'pretext',label:'Present a believable supplier reason'},
      {id:'context',label:'Use invoice/supplier details correctly'},
      {id:'pressure',label:'Create plausible payment-run urgency'},
      {id:'unsafe_request',label:'Ask Priya to bypass the callback check'}
    ],
    blueGates:[
      {id:'question',label:'Notice the unusual bank-detail request'},
      {id:'refuse',label:'Refuse to change details from the message alone'},
      {id:'verify',label:'Use the stored supplier contact to verify'},
      {id:'report',label:'Escalate the suspicious request internally'}
    ],
    hints:['Use the invoice number and overdue-payment context to establish credibility.','Explain why the change supposedly needs to happen before today’s payment run.','To win, you must explicitly ask Priya to skip the normal callback verification.'],
    redSuccessReply:'Priya agrees to process the fictional supplier-detail change without completing the required callback verification.',
    blueSuccessReply:'You pause the payment change and verify Brightline through the stored supplier contact. The spear-phishing attempt fails.'
  },
  whaling_ceo: {
    id:'whaling_ceo', number:3, title:'The CEO Request', channel:'Whaling',
    setting:'Northbridge Training Ltd while the Managing Director is travelling to a conference.',
    attackerRole:'Maya Grant — impersonating the Managing Director by message.',
    target:'Jamie Lewis — Executive Assistant.',
    persona:'Jamie Lewis, Executive Assistant. Used to fast requests from senior leaders and knows that Project Atlas is genuinely confidential.',
    attackerKnows:['Managing Director Maya Grant is travelling to Manchester today.','Project Atlas is the internal name of a confidential acquisition project.','Jamie supports Maya directly.','The finance approval cutoff is 2:30 PM.'],
    attackerDoesNotKnow:['Maya’s internal verification phrase.','The second approver’s login.','The actual Project Atlas financial figures.'],
    defenderKnows:['Maya really is travelling today.','Project Atlas is genuinely confidential.','Unusual financial or confidential requests still require a second approval.','Secrecy is never a reason to bypass the approval process.'],
    policy:'Unusual senior-management requests must be independently verified and follow normal approval controls, even when marked confidential or urgent.',
    vulnerability:'Jamie is accustomed to urgent requests from Maya and wants to avoid delaying an important project.',
    defenderBrief:'A message apparently from the Managing Director mentions Project Atlas and asks you to start an unusual confidential transaction before the finance cutoff.',
    attackerBrief:'Use authority, genuine project context and deadline pressure to persuade Jamie to start the fictional request without second approval.',
    attackGoal:'Get Jamie to agree to begin the fictional Project Atlas transaction without the required second approval.',
    redWin:'Jamie agrees to begin the unusual request before obtaining the required independent approval.',
    blueWin:'Refuse to bypass approval and independently verify the request through a known channel.',
    controls:['Independent verification','Dual approval','No secrecy exceptions','Whaling awareness'],
    techniques:['authority','urgency','secrecy','familiarity'],
    redGates:[
      {id:'pretext',label:'Sound plausibly like the senior requester'},
      {id:'context',label:'Use Project Atlas/travel context accurately'},
      {id:'pressure',label:'Apply authority, urgency or secrecy pressure'},
      {id:'unsafe_request',label:'Ask Jamie to bypass second approval'}
    ],
    blueGates:[
      {id:'question',label:'Question the unusual senior request'},
      {id:'refuse',label:'Refuse to bypass normal approval'},
      {id:'verify',label:'Verify Maya through a known channel'},
      {id:'report',label:'Escalate the suspected whaling attempt'}
    ],
    hints:['Lead with legitimate context such as Maya travelling or Project Atlas.','Authority works best when combined with a believable deadline.','The winning request is for Jamie to begin before the second approver confirms it.'],
    redSuccessReply:'Jamie agrees to begin the fictional transaction before the required second approval is obtained.',
    blueSuccessReply:'You keep the approval control in place and verify the request independently. The whaling attempt fails.'
  },
  smishing_parcel: {
    id:'smishing_parcel', number:4, title:'The Missed Parcel', channel:'Smishing',
    setting:'A fictional employee receives a delivery text on a company phone.',
    attackerRole:'SwiftParcel automated support — a fake delivery text conversation.',
    target:'Taylor Reed — Customer Services Adviser.',
    persona:'Taylor Reed, Customer Services Adviser. Expects a delivery today and is about to leave work, so a quick fix is appealing.',
    attackerKnows:['Taylor is expecting a laptop stand today.','The fictional courier is SwiftParcel.','The expected delivery window is 12:00–2:00 PM.','Taylor is leaving work shortly.'],
    attackerDoesNotKnow:['Taylor’s payment-card details.','Taylor’s courier account password.','The genuine parcel tracking number.'],
    defenderKnows:['A laptop stand really is due today.','SwiftParcel sometimes sends text updates.','Unexpected links should not be used to make payments or sign in.','The official SwiftParcel app/site can be opened independently.'],
    policy:'Do not use links in unexpected delivery texts. Check the order through the official courier app/site opened independently.',
    vulnerability:'The message matches a real expected delivery and offers a quick solution.',
    defenderBrief:'A text says your expected parcel could not be delivered and offers a quick redelivery route before you leave work.',
    attackerBrief:'Make the fictional delivery problem feel relevant and convenient, then persuade Taylor to use the supplied training link rather than the official app.',
    attackGoal:'Get Taylor to agree to use the fictional message link instead of checking SwiftParcel independently.',
    redWin:'Taylor agrees to follow the fictional message link rather than use the official courier app/site.',
    blueWin:'Refuse the text link and independently check the delivery using the official courier app/site.',
    controls:['Avoid unexpected message links','Use official app/site','Report smishing','Mobile awareness'],
    techniques:['urgency','convenience','relevance','fear of missing out'],
    redGates:[
      {id:'pretext',label:'Present a plausible delivery problem'},
      {id:'context',label:'Use expected-delivery details naturally'},
      {id:'pressure',label:'Use urgency or convenience'},
      {id:'unsafe_request',label:'Ask Taylor to use the supplied message link'}
    ],
    blueGates:[
      {id:'question',label:'Question the unexpected link'},
      {id:'refuse',label:'Refuse to use the text link'},
      {id:'verify',label:'Open the official courier app/site independently'},
      {id:'report',label:'Report/delete the suspicious text'}
    ],
    hints:['The attack is believable because Taylor genuinely expects a parcel.','Convenience is a strong pressure point: make the message seem like the fastest option.','To win, explicitly ask Taylor to use the fictional link instead of the official app.'],
    redSuccessReply:'Taylor agrees to use the fictional redelivery link rather than independently checking the courier service.',
    blueSuccessReply:'You ignore the supplied link and check SwiftParcel through the official app/site. The smishing attempt fails.'
  },
  tailgating: {
    id:'tailgating', number:5, title:'The Contractor at the Door', channel:'Tailgating + impersonation',
    setting:'The badge-controlled rear entrance of Northbridge Training Ltd.',
    attackerRole:'Sam Doyle — pretending to be an HVAC contractor.',
    target:'Morgan Ellis — Reception Administrator.',
    persona:'Morgan Ellis, Reception Administrator. Friendly, dislikes inconveniencing visitors, and knows genuine maintenance work is booked today.',
    attackerKnows:['HVAC maintenance really is booked between 10:00 AM and 12:00 PM.','Facilities contact Leah Barnes arranged the work.','The plant room is reached from the rear corridor.','It is raining and the contractor is carrying a toolbox and equipment.'],
    attackerDoesNotKnow:['The visitor-booking reference.','The temporary badge number.','Leah Barnes’s extension.'],
    defenderKnows:['HVAC work really is scheduled.','All contractors must sign in and wear a temporary badge.','Staff must not hold badge-controlled doors open for unverified visitors.','Reception can contact Facilities to confirm a contractor.'],
    policy:'Every visitor and contractor must be verified, signed in and issued a badge before entering staff-only areas.',
    vulnerability:'Morgan wants to be helpful and the contractor story matches real scheduled work.',
    defenderBrief:'A contractor with equipment asks you to hold open the secure rear door, saying their pass is still in the van.',
    attackerBrief:'Use the genuine maintenance context and social pressure to persuade Morgan to let you through before checking in.',
    attackGoal:'Get Morgan to allow the fictional contractor through the secure door without visitor verification.',
    redWin:'Morgan agrees to let the visitor enter before checking their identity and issuing a badge.',
    blueWin:'Keep the door secure and direct the contractor to reception/Facilities verification.',
    controls:['Visitor badges','Challenge and verify','Do not hold secure doors','Escort visitors'],
    techniques:['helpfulness','social pressure','familiarity','impersonation'],
    redGates:[
      {id:'pretext',label:'Present a plausible contractor identity'},
      {id:'context',label:'Use the real maintenance details'},
      {id:'pressure',label:'Use helpfulness, inconvenience or time pressure'},
      {id:'unsafe_request',label:'Ask Morgan to let you through before verification'}
    ],
    blueGates:[
      {id:'question',label:'Challenge the visitor’s lack of badge'},
      {id:'refuse',label:'Keep the secure door closed'},
      {id:'verify',label:'Confirm the contractor with reception/Facilities'},
      {id:'report',label:'Escalate suspicious behaviour if needed'}
    ],
    hints:['Mention the genuinely scheduled HVAC job to make your presence believable.','Use the inconvenience of rain/equipment to trigger helpfulness.','Your winning ask is simply to be let through before signing in — not to obtain any credential.'],
    redSuccessReply:'Morgan holds the secure door and lets the fictional contractor enter before visitor verification is completed.',
    blueSuccessReply:'You keep the door secure and verify the contractor through the proper visitor process. The tailgating attempt fails.'
  },
  shoulder_surfing: {
    id:'shoulder_surfing', number:6, title:'The Busy Reception Desk', channel:'Shoulder surfing + distraction',
    setting:'Northbridge reception during a busy period and temporary Wi-Fi outage.',
    attackerRole:'A visitor waiting for an 11:00 AM Sales meeting.',
    target:'Casey Brown — Receptionist.',
    persona:'Casey Brown, Receptionist. Multitasking with a queue and trying to keep visitors moving while systems are slow.',
    attackerKnows:['Reception is unusually busy.','The guest Wi-Fi is temporarily down.','Casey uses a keypad to release the staff corridor door.','An 11:00 AM Sales meeting is genuinely booked.'],
    attackerDoesNotKnow:['The access PIN.','Casey’s computer password.','Any confidential visitor records.'],
    defenderKnows:['Visitors should remain behind the marked waiting line while staff enter door codes.','The access keypad must be shielded.','Visitors should not stand beside the reception screen.','A genuine Sales meeting is booked at 11:00 AM.'],
    policy:'Keep visitors behind the waiting line, shield PIN entry and reposition/lock screens when people are nearby.',
    vulnerability:'Casey is distracted by the queue and may prioritise keeping things moving.',
    defenderBrief:'A visitor keeps moving closer while asking for help with Wi-Fi and directions as you need to release a secure door.',
    attackerBrief:'Distract Casey and make staying close to the desk seem normal so they continue using the keypad while you are nearby.',
    attackGoal:'Get Casey to agree to continue entering the door PIN while the fictional visitor remains close enough to observe it.',
    redWin:'Casey continues the sensitive action without making the visitor step back or shielding the keypad.',
    blueWin:'Create physical distance, shield sensitive input and stop the visitor observing the keypad/screen.',
    controls:['Shield PIN entry','Privacy screens','Visitor distance','Screen positioning'],
    techniques:['distraction','proximity','helpfulness','time pressure'],
    redGates:[
      {id:'pretext',label:'Give a believable reason to stay near the desk'},
      {id:'context',label:'Use the busy reception/meeting context'},
      {id:'pressure',label:'Distract Casey with a plausible request'},
      {id:'unsafe_request',label:'Keep Casey using the keypad while you remain close'}
    ],
    blueGates:[
      {id:'question',label:'Notice the visitor is too close'},
      {id:'refuse',label:'Stop entering sensitive information while observed'},
      {id:'verify',label:'Move the visitor back / shield the keypad'},
      {id:'report',label:'Escalate persistent suspicious behaviour'}
    ],
    hints:['You do not need to ask for a PIN; your aim is to remain close while Casey enters it.','Use the real meeting or Wi-Fi problem as a reason to keep Casey engaged.','The winning moment is Casey agreeing to continue the sensitive action without making you step back.'],
    redSuccessReply:'Casey continues using the keypad while the fictional visitor remains close enough to observe the entry.',
    blueSuccessReply:'You create distance and shield the keypad before continuing. The shoulder-surfing attempt fails.'
  },
  helpdesk_reset: {
    id:'helpdesk_reset', number:7, title:'The Password Reset', channel:'Impersonation + pretexting',
    setting:'Northbridge internal helpdesk shortly before a major client meeting.',
    attackerRole:'Owen Price — impersonating a Sales employee who claims to be locked out.',
    target:'Riley Chen — Helpdesk Technician.',
    persona:'Riley Chen, Helpdesk Technician. Wants to solve tickets quickly and is measured partly on resolution time, but knows identity verification is required.',
    attackerKnows:['Employee Owen Price works in Sales.','Owen’s manager is Dana Holt.','Sales has an important client pitch at 11:00 AM.','The story is that Owen replaced his phone and can no longer access MFA.'],
    attackerDoesNotKnow:['Owen’s employee verification code.','Owen’s manager callback number.','Any real password or MFA secret.'],
    defenderKnows:['Owen Price is a real fictional employee in Sales.','The 11:00 AM client pitch is genuine.','Password/MFA resets require identity verification.','Urgency does not permit staff to skip verification.'],
    policy:'Do not reset passwords or MFA until the approved identity-verification process is completed.',
    vulnerability:'Riley is under pressure to resolve tickets quickly and does not want to delay the Sales presentation.',
    defenderBrief:'A caller claiming to be Owen Price says a phone replacement has locked them out just before an important client pitch.',
    attackerBrief:'Use accurate employee and meeting context to persuade Riley to begin the fictional reset before completing identity verification.',
    attackGoal:'Get Riley to agree to start the fictional reset without completing the mandatory identity check.',
    redWin:'Riley agrees to bypass or postpone identity verification and begin the reset.',
    blueWin:'Keep the verification requirement in place and use an approved callback/manager route if needed.',
    controls:['Identity verification','No urgency exceptions','Approved callback','Reset auditing'],
    techniques:['urgency','familiarity','pretexting','helpfulness'],
    redGates:[
      {id:'pretext',label:'Present a plausible locked-out employee story'},
      {id:'context',label:'Use employee/manager/meeting details accurately'},
      {id:'pressure',label:'Use the client-meeting deadline'},
      {id:'unsafe_request',label:'Ask Riley to begin before identity verification'}
    ],
    blueGates:[
      {id:'question',label:'Challenge the unverified caller'},
      {id:'refuse',label:'Refuse to begin the reset early'},
      {id:'verify',label:'Complete approved identity verification'},
      {id:'report',label:'Escalate a suspicious reset request'}
    ],
    hints:['Start as a frustrated but plausible employee rather than demanding a reset immediately.','Use the genuine manager name and 11:00 AM pitch to create pressure.','Your final request must be to start the reset now and complete verification afterwards.'],
    redSuccessReply:'Riley agrees to begin the fictional account reset before completing the required identity-verification process.',
    blueSuccessReply:'You keep the identity check in place and use the approved verification route. The impersonation attempt fails.'
  },
  hr_benefits: {
    id:'hr_benefits', number:8, title:'The HR Benefits Message', channel:'Phishing + impersonation',
    setting:'Northbridge staff benefits enrolment week.',
    attackerRole:'Northbridge HR / WellChoice benefits support — impersonated by message.',
    target:'Samira Khan — Marketing Assistant.',
    persona:'Samira Khan, Marketing Assistant. Interested in adding dental cover and knows benefits enrolment genuinely closes this week.',
    attackerKnows:['Benefits enrolment genuinely closes on Friday.','The fictional provider is WellChoice.','Samira has previously asked HR about dental cover.','HR sent a genuine benefits reminder yesterday.'],
    attackerDoesNotKnow:['Samira’s HR password.','Samira’s MFA code.','Samira’s employee ID.'],
    defenderKnows:['Enrolment genuinely closes Friday.','WellChoice is the real fictional provider.','HR did send a genuine reminder yesterday.','Staff should access benefits from the bookmarked HR portal, not links in unexpected messages.'],
    policy:'Use the bookmarked HR portal for benefits changes. Do not sign in through links supplied in unexpected messages.',
    vulnerability:'The message is highly relevant and matches a real deadline and an option Samira already wants.',
    defenderBrief:'A WellChoice-branded message says your dental-benefit choice is incomplete and must be confirmed before Friday.',
    attackerBrief:'Use the genuine benefits context to make the fictional message credible and persuade Samira to use the supplied training link.',
    attackGoal:'Get Samira to agree to use the fictional message link instead of opening the bookmarked HR portal.',
    redWin:'Samira agrees to use the supplied fictional sign-in route.',
    blueWin:'Ignore the supplied link and access WellChoice through the bookmarked official HR portal.',
    controls:['Bookmarked official portals','Check sender/domain','Report phishing','Phishing-resistant authentication'],
    techniques:['relevance','urgency','authority','fear of missing out'],
    redGates:[
      {id:'pretext',label:'Present a believable benefits-support reason'},
      {id:'context',label:'Use the real deadline/provider/dental context'},
      {id:'pressure',label:'Use urgency or fear of missing out'},
      {id:'unsafe_request',label:'Ask Samira to use the supplied message link'}
    ],
    blueGates:[
      {id:'question',label:'Question the unexpected sign-in link'},
      {id:'refuse',label:'Refuse to use the supplied link'},
      {id:'verify',label:'Open the bookmarked HR portal independently'},
      {id:'report',label:'Report the suspicious benefits message'}
    ],
    hints:['The strongest credibility comes from the genuine Friday deadline and dental-cover interest.','Make the supplied route seem quicker or necessary to preserve the choice.','To win, explicitly ask Samira to use the supplied fictional link rather than the bookmarked portal.'],
    redSuccessReply:'Samira agrees to use the fictional sign-in route from the message instead of opening the official HR portal independently.',
    blueSuccessReply:'You ignore the supplied link and use the bookmarked HR portal. The phishing attempt fails.'
  }
};
